-- TULOSYKSIKKÖ TASO
INSERT INTO
    OrganizationTree (Number, Name, ParentNumber, Alue, ParentAlue)
VALUES
    (
        '1000',
        'VAALIT',
        '1000',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1200',
        'TARKASTUSTOIMI',
        '1000',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1300',
        'YLEISHALLINTO',
        '1300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1410',
        'PÄÄTÖSVALMISTELU',
        '1400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1500',
        'HENKILÖSTÖPALVELUT',
        '1500',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1610',
        'TALOUSHALLINTO',
        '1600',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1650',
        'TIETOHALLINTO',
        '1600',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1680',
        'HANKINTA- JA VARASTOPALVELUT',
        '1600',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '1480',
        'MAASEUTUPALVELUT',
        '1400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '8900',
        'RAHOITUS',
        '8900',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4000',
        'SIVISTYKSEN JA HYVINVOINNIN TOIMIALAN HALLINTO',
        '4000',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4100',
        'PERUSOPETUS',
        '4100',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4200',
        'ERITYISOPETUS',
        '4200',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4250',
        'APIP-TOIMINTA',
        '4200',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4300',
        'VARHAISKASVATUKSEN HALLINTO',
        '4300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4400',
        'PÄIVÄKODIT',
        '4400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4420',
        'JOUPPI-KATAJALAAKSON ALUE',
        '4400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4460',
        'KESKUSTAN ALUE',
        '4400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4490',
        'KASPERI-KIVISTÖN ALUE',
        '4400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4540',
        'PERÄSEINÄJOEN-KÄRJEN ALUE',
        '4400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4580',
        'NURMON ALUE',
        '4400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4640',
        'YLISTARO-NURMON ALUE',
        '4400',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4660',
        'YLISTARO-NURMON ALUE',
        '4500',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4570',
        'PERÄSEINÄJOEN-KÄRJEN ALUE',
        '4600',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4710',
        'MUU PÄIVÄHOITO',
        '4710',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4770',
        'VARHAISERITYISKASVATUS',
        '4770',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4700',
        'PERHEPÄIVÄHOITO',
        '4700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4720',
        'AVOIN LEIKKITOIMINTA',
        '4720',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4800',
        'LUKIOKOULUTUS',
        '4800',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '4900',
        'KANSALAISOPISTO',
        '4900',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '5100',
        'KIRJASTOPALVELUT',
        '5100',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '5300',
        'KULTTUURIPALVELUT',
        '5300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '5500',
        'MUSEOPALVELUT',
        '5500',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '5700',
        'LIIKUNTAPALVELUT',
        '5700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '5900',
        'NUORISOPALVELUT',
        '5900',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6000',
        'KAUPUNKIYMPÄRISTÖLAUTAKUNTA',
        '6000',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6010',
        'KAUPUNKIYMPÄRISTÖ',
        '6000',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6020',
        'LUPA-ASIAINLAUTAKUNTA',
        '6000',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6100',
        'TOIMITILAT',
        '6100',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6110',
        'YLLÄPITOPALVELUT',
        '6100',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6120',
        'RUOKA- JA SIIVOUSPALVELUT',
        '6100',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6200',
        'KIIINTEISTÖ- JA PAIKKATIETOPALVELUT',
        '6200',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6310',
        'SUUNNITTELU',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6320',
        'RAKENTAMINEN',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6340',
        'LASKUTETTAVAT TYÖT',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6360',
        'JÄTEHUOLTO',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6380',
        'LIIKENNEVÄYLÄT',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6390',
        'KUNNOSSAPITO',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6420',
        'VARIKKOTOIMINNOT',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6440',
        'KULJETUSKESKUS',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6460',
        'PUISTOTOIMI',
        '6300',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6500',
        'KAUPUNKISUUNNITTELU JA KAAVOITUS',
        '6500',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6600',
        'RAKENNUSVALVONTA',
        '6600',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6700',
        'YMPÄRISTÖNSUOJELU',
        '6700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '6900',
        'YMPÄRISTÖTERVEYDENHUOLTO',
        '6900',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7100',
        'STRATEGIATYÖ',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7150',
        'ALUEKEHITYS JA KORKEAKOULUYHTEISTYÖ',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7160',
        'HANKEKEHITYS',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7200',
        'MARKKINOINTI',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7250',
        'VIESTINTÄ',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7300',
        'KANSAINVÄLISET ASIAT',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7350',
        'PAKOLAISTYÖ',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7400',
        'HYVINVOINTI JA OSALLISUUS',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7450',
        'TOIMINTOJEN TALO',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7600',
        'TAPAHTUMAT',
        '700',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    ),
    (
        '7110',
        'TYÖLLISYYSPALVELUT',
        '710',
        'TULOSYKSIKKÖ',
        'VASTUUALUE'
    );

GO
