INSERT INTO
    PositionNames (Name, ValidFrom, ValidUntil)
VALUES
    ('aamu- ja iltapäivätoim. koordinaattori', NULL, NULL),
    ('aamu- ja iltapäivätoiminnan ohjaaja', NULL, NULL),
    ('aamu-ja iltapäivätoiminnan ohjaaja', NULL, NULL),
    ('aikuis- ja eläketoiminnan ohjaaja', NULL, NULL),
    ('aluekoordinaattori', NULL, NULL),
    ('amanuenssi', NULL, NULL),
    ('ammattimies', NULL, NULL),
    ('apulaisrehtori', NULL, NULL),
    ('arkeologi', NULL, NULL),
    ('arkistoapulainen', NULL, NULL),
    ('arkistosihteeri', NULL, NULL),
    ('asemakaavapäällikkö', NULL, NULL),
    ('asiakaspalvelija', NULL, NULL),
    ('asiakaspalvelusihteeri', NULL, NULL),
    ('asiakaspalveluvastaava', NULL, NULL),
    ('asiantuntija', NULL, NULL),
    ('assistentti', NULL, NULL),
    ('asuntoasiain sihteeri', NULL, NULL),
    ('autonkuljettaja', NULL, NULL),
    ('autonkuljettaja, vanh.', NULL, NULL),
    ('controller', NULL, NULL),
    ('dieettikokki', NULL, NULL),
    ('digineuvoja', NULL, NULL),
    ('ehkäisevän päihdetyön koordinaattori', NULL, NULL),
    ('elinvoimajohtaja', NULL, NULL),
    ('eläintenhoitaja', NULL, NULL),
    ('englannin- ja ruotsinkielen lehtori', NULL, NULL),
    ('erikoisammattihenkilö', NULL, NULL),
    ('erikoiskirjastovirkailija', NULL, NULL),
    ('erikoissuunnittelija', NULL, NULL),
    ('erityiskoulun johtajaopettaja', NULL, NULL),
    ('erityisliikunnan koordinaattori', NULL, NULL),
    ('erityisluokan opettaja', NULL, NULL),
    ('erityisluokanopett., kuulovamm. opetus', NULL, NULL),
    ('erityisluokanopett., mukautettu ope', NULL, NULL),
    ('erityisluokanopett., mukautettu opetus', NULL, NULL),
    ('erityisluokanopett., sopeutumatt. opetus', NULL, NULL),
    ('erityisluokanopett., vammaisten opetus', NULL, NULL),
    ('erityisluokanopettaja, harjaantumisopet.', NULL, NULL),
    ('erityisluokanopettaja/erityisopettaja', NULL, NULL),
    ('erityisnuorisotyöntekijä', NULL, NULL),
    ('erityisohjaaja', NULL, NULL),
    ('erityisopettaja,muu kuin peruskoulussa', NULL, NULL),
    ('erityisopettaja,peruskoulussa', NULL, NULL),
    ('esiintyjä', NULL, NULL),
    ('esimies', NULL, NULL),
    ('etsivä nuorisotyöntekijä', NULL, NULL),
    ('hallimestari', NULL, NULL),
    ('hallintojohtaja', NULL, NULL),
    ('hallintokoordinaattori', NULL, NULL),
    ('hallintopäällikkö', NULL, NULL),
    ('hallintosihteeri', NULL, NULL),
    ('hankepäällikkö', NULL, NULL),
    ('hankinta- ja varastopäällikkö', NULL, NULL),
    ('hankinta-asiantuntija', NULL, NULL),
    ('hankintajohtaja', NULL, NULL),
    ('harjoittelija', NULL, NULL),
    ('henkilökohtainen avustaja', NULL, NULL),
    ('henkilöstöjohtaja', NULL, NULL),
    ('henkilöstökoordinaattori', NULL, NULL),
    ('hoitaja', NULL, NULL),
    ('huolto- ja korjausmies', NULL, NULL),
    ('huoltomies', NULL, NULL),
    ('hygieenikkoeläinlääkäri', NULL, NULL),
    ('hyvinvointipäällikkö', NULL, NULL),
    ('ict-asiantuntija', NULL, NULL),
    ('ict-kehittämispäällikkö', NULL, NULL),
    ('ict-palveluvastaava', NULL, NULL),
    ('ict-suunnittelija', NULL, NULL),
    ('ict-tukihenkilö', NULL, NULL),
    ('iltapäivätoiminnan ohjaaja', NULL, NULL),
    ('iltapäivätoiminnanohjaaja', NULL, NULL),
    ('informaatikko', NULL, NULL),
    ('intendentti', NULL, NULL),
    ('isännöintipäällikkö', NULL, NULL),
    ('it-tukihenkilö', NULL, NULL),
    ('johdon assistentti', NULL, NULL),
    ('johdon sihteeri', NULL, NULL),
    ('johtava kaupungineläinlääkäri', NULL, NULL),
    ('johtava rakennustarkastaja', NULL, NULL),
    ('julkisen taiteen koordinaattori', NULL, NULL),
    ('järjestötyönkoordinaattori', NULL, NULL),
    ('kaavasuunnittelija', NULL, NULL),
    ('kaavoitusarkkitehti', NULL, NULL),
    ('kaavoitusassistentti', NULL, NULL),
    ('kaavoitusjohtaja', NULL, NULL),
    ('kahvilatyöntekijä', NULL, NULL),
    ('kaivinkoneenkuljettaja', NULL, NULL),
    ('kalustonkorjaaja', NULL, NULL),
    ('kansainvälisten asioiden koordinaattori', NULL, NULL),
    ('kansalaisopiston opettaja', NULL, NULL),
    ('kansalaisopiston rehtori', NULL, NULL),
    ('kartoittaja', NULL, NULL),
    ('karttaoperaattori', NULL, NULL),
    ('kaupunginarkkitehti', NULL, NULL),
    ('kaupungineläinlääkäri', NULL, NULL),
    ('kaupungingeodeetti', NULL, NULL),
    ('kaupungininsinööri', NULL, NULL),
    ('kaupunginjohtaja', NULL, NULL),
    ('kaupunginpuutarhuri', NULL, NULL),
    ('kaupunkiympäristöjohtaja', NULL, NULL),
    ('kehittäjä', NULL, NULL),
    ('kehittämispäällikkö', NULL, NULL),
    ('kehitysinsinööri', NULL, NULL),
    ('kehityspäällikkö', NULL, NULL),
    ('kerho-ohjaaja', NULL, NULL),
    ('kesäsiirtolan apulaisjohtaja', NULL, NULL),
    ('kesäsiirtolan johtaja', NULL, NULL),
    ('kesäsiirtolan ohjaaja', NULL, NULL),
    ('kesätyöntekijä/kunnossapito', NULL, NULL),
    ('kesätyöntekijä/taiteilija', NULL, NULL),
    ('kierrätystyöntekijä', NULL, NULL),
    ('kiinteistöapulainen', NULL, NULL),
    ('kiinteistöinsinööri', NULL, NULL),
    ('kiinteistömestari', NULL, NULL),
    ('kiinteistönhoitaja', NULL, NULL),
    ('kiinteistörekisterinhoitaja', NULL, NULL),
    ('kiinteistösihteeri', NULL, NULL),
    ('kiinteistötyönjohtaja', NULL, NULL),
    ('kirjanpitopäällikkö', NULL, NULL),
    ('kirjanpitäjä', NULL, NULL),
    ('kirjastoautonkuljettaja', NULL, NULL),
    ('kirjastoautonkuljettaja-virkailija', NULL, NULL),
    ('kirjastoavustaja', NULL, NULL),
    ('kirjastonhoitaja', NULL, NULL),
    ('kirjastotoimenjohtaja', NULL, NULL),
    ('kirjastovirkailija', NULL, NULL),
    ('kirvesmiehen apulainen', NULL, NULL),
    ('kirvesmies', NULL, NULL),
    ('kirvesmies, vanhempi', NULL, NULL),
    ('kirvesmies-työnjohtaja', NULL, NULL),
    ('kokki', NULL, NULL),
    ('koneteknikko', NULL, NULL),
    ('konsernikirjanpitäjä', NULL, NULL),
    ('konservaattori', NULL, NULL),
    ('koordinaattori', NULL, NULL),
    ('korjausmies', NULL, NULL),
    ('koulunkäynnin ohjaaja', NULL, NULL),
    ('koulunkäynninohjaaja-laitosapulainen', NULL, NULL),
    ('koulunkäyntiavustaja', NULL, NULL),
    ('koulusihteeri', NULL, NULL),
    ('kouluvalmentaja', NULL, NULL),
    ('kuljetuskoordinaattori', NULL, NULL),
    ('kuljetussuunnittelija', NULL, NULL),
    ('kulttuurikasvatussuunnitelmakoordinaatto', NULL, NULL),
    ('kulttuuriohjaaja', NULL, NULL),
    ('kulttuuripalvelupäällikkö', NULL, NULL),
    ('kulttuuritoimen johtaja', NULL, NULL),
    ('kulttuurituottaja', NULL, NULL),
    ('kunnallistekniikan suunnittelija', NULL, NULL),
    ('kunnallistekniikan työntekijä', NULL, NULL),
    ('kunnossapitomestari', NULL, NULL),
    ('kunnossapitopäällikkö', NULL, NULL),
    ('kunnossapitotyöntekijä', NULL, NULL),
    ('kuorma-autonkuljettaja', NULL, NULL),
    ('laitoshuoltaja', NULL, NULL),
    ('laitosmies', NULL, NULL),
    ('lastenkulttuurikoordinaattori', NULL, NULL),
    ('leipuri', NULL, NULL),
    ('liikunnanohjaaja', NULL, NULL),
    ('liikuntapaikan hoitaja', NULL, NULL),
    ('liikuntapaikanhoitaja', NULL, NULL),
    ('liikuntapaikkamestari', NULL, NULL),
    ('liikuntapaikkasuunnittelija', NULL, NULL),
    ('liikuntapaikkatyöntekijä', NULL, NULL),
    ('liikuntapaikkojen hoitaja', NULL, NULL),
    ('liikuntapaikkojen kunnossapitotyönt', NULL, NULL),
    ('liikuntapalvelupäällikkö', NULL, NULL),
    ('liikuntatoimenjohtaja', NULL, NULL),
    ('logistiikkapäällikkö', NULL, NULL),
    ('lukion aikuislinjan lehtori ruotsi ja ranska', NULL, NULL),
    ('lukion aikuislinjan lehtori, englanti', NULL, NULL),
    ('lukion erityisopettaja', NULL, NULL),
    ('lukion ja aikuislinjan lehtori, äid', NULL, NULL),
    ('lukion ja peruskoulun yhteinen lehtori', NULL, NULL),
    ('lukion ja perusopetuksen yht.leht.', NULL, NULL),
    ('lukion lehtori', NULL, NULL),
    ('lukion lehtori, uskonto ja psykologia', NULL, NULL),
    ('lukion lehtori,kuvataide', NULL, NULL),
    ('lukion opinto-ohjaaja', NULL, NULL),
    ('lukion rehtori', NULL, NULL),
    ('luokanopettaja', NULL, NULL),
    ('lupa-assistentti', NULL, NULL),
    ('lupainsinööri', NULL, NULL),
    ('lvi-asentaja', NULL, NULL),
    ('lvi-insinööri', NULL, NULL),
    ('lvi-tarkastaja', NULL, NULL),
    ('lähiesimies', NULL, NULL),
    ('lähihoitaja', NULL, NULL),
    ('lähipalvelujohtaja', NULL, NULL),
    ('maahanmuuttotyön koordinaattori', NULL, NULL),
    ('maankäyttöinsinööri', NULL, NULL),
    ('maanmittausharjoittelija', NULL, NULL),
    ('maanrakennusammattimies', NULL, NULL),
    ('maanrakennusmestari', NULL, NULL),
    ('maanrakennustyöntekijä', NULL, NULL),
    ('maarakennusmestari', NULL, NULL),
    ('maaseutupäällikkö', NULL, NULL),
    ('maastomittausteknikko', NULL, NULL),
    ('maatalouspäällikkö', NULL, NULL),
    ('markkinointipäällikkö', NULL, NULL),
    ('mittausinsinööri', NULL, NULL),
    ('mittausmies', NULL, NULL),
    ('mittausmies, vanh.', NULL, NULL),
    ('mittaustyönjohtaja', NULL, NULL),
    ('monistussihteeri', NULL, NULL),
    ('museoamanuenssi', NULL, NULL),
    ('museoapulainen', NULL, NULL),
    ('museoassistentti', NULL, NULL),
    ('museolehtori', NULL, NULL),
    ('museomestari', NULL, NULL),
    ('museonhoitaja', NULL, NULL),
    ('museotoimen johtaja', NULL, NULL),
    ('museotyöntekijä', NULL, NULL),
    ('nuoriso-ohjaaja', NULL, NULL),
    ('nuorisopalvelupäällikkö', NULL, NULL),
    ('nuorisotoimenjohtaja', NULL, NULL),
    ('näyttelyavustaja', NULL, NULL),
    ('näyttelymestari', NULL, NULL),
    ('ohjaaja', NULL, NULL),
    ('omavalmentaja', NULL, NULL),
    ('opas', NULL, NULL),
    ('opetustoimenjohtaja', NULL, NULL),
    ('opistomestari', NULL, NULL),
    ('oppilaanohjauksen lehtori', NULL, NULL),
    ('paikkatietoasiantuntija', NULL, NULL),
    ('paikkatietosuunnittelija', NULL, NULL),
    ('pakolaiskoordinaattori', NULL, NULL),
    ('pakolaistyöntekijä', NULL, NULL),
    ('palkkasihteeri', NULL, NULL),
    ('palveluesimies', NULL, NULL),
    ('palvelukoordinaattori', NULL, NULL),
    ('palveluneuvoja', NULL, NULL),
    ('palveluohjaaja', NULL, NULL),
    ('palvelupäällikkö', NULL, NULL),
    ('palvelusihteeri', NULL, NULL),
    ('palvelutyöntekijä', NULL, NULL),
    ('palveluvastaava', NULL, NULL),
    ('perhepäivähoidon ohjaaja', NULL, NULL),
    ('perhepäivähoitaja', NULL, NULL),
    ('perhepäivähoitaja, kiertävä', NULL, NULL),
    ('peruskoulun ja lukion yhteinen lehtori', NULL, NULL),
    ('peruskoulun johtaja', NULL, NULL),
    ('peruskoulun lehtori', NULL, NULL),
    ('peruskoulun luokanopettaja', NULL, NULL),
    ('peruskoulun rehtori', NULL, NULL),
    ('perusopetuksen ja lukion lehtori', NULL, NULL),
    ('perusopetuksen lehtori', NULL, NULL),
    ('perusopetuksen luokanopettaja', NULL, NULL),
    ('perusopetusjohtaja', NULL, NULL),
    ('piirtäjä-operaattori', NULL, NULL),
    ('projekti-insinööri', NULL, NULL),
    ('projektikoordinaattori', NULL, NULL),
    ('projektipäällikkö', NULL, NULL),
    ('projektitutkija', NULL, NULL),
    ('projektityöntekijä', NULL, NULL),
    ('puhelinpalvelusihteeri', NULL, NULL),
    ('puhelinvaihteenhoitaja', NULL, NULL),
    ('puisto- ja puutarhatyöntekijä', NULL, NULL),
    ('puistomestari', NULL, NULL),
    ('puistotyöntekijä', NULL, NULL),
    ('puistotyöntekijä, täysin amm.t', NULL, NULL),
    ('puistotyöntekijä, täysin amm.tait. yli 6', NULL, NULL),
    ('putkiasentaja, vanhempi maanrak.', NULL, NULL),
    ('puutarhuri', NULL, NULL),
    ('pysäköinnintarkastaja', NULL, NULL),
    ('päiväkodin apulaisjohtaja', NULL, NULL),
    ('päiväkodin johtaja', NULL, NULL),
    ('päiväkodin opettaja', NULL, NULL),
    ('päiväkotihuoltaja', NULL, NULL),
    ('pääkirjanpitäjä', NULL, NULL),
    ('pääluottamusmies', NULL, NULL),
    ('rahoitusjohtaja', NULL, NULL),
    ('rahoitussuunnittelija', NULL, NULL),
    ('rakennusammattihenkilö', NULL, NULL),
    ('rakennusarkkitehti', NULL, NULL),
    ('rakennustarkastaja', NULL, NULL),
    ('rakennustekninen valvoja', NULL, NULL),
    ('rakennustutkija', NULL, NULL),
    ('rakennuttajainsinööri', NULL, NULL),
    ('rakennuttajapäällikkö', NULL, NULL),
    ('rantavalvoja', NULL, NULL),
    ('ravitsemistyönjohtaja', NULL, NULL),
    ('ravitsemistyöntekijä', NULL, NULL),
    ('ravitsemustyöntekijä', NULL, NULL),
    ('rehtori', NULL, NULL),
    ('resurssiopettaja', NULL, NULL),
    ('ruoka- ja siivouspalvelupäällikkö', NULL, NULL),
    ('ruokapalveluasiantuntija', NULL, NULL),
    ('ruokapalveluesihenkilö', NULL, NULL),
    ('ruokapalvelutyöntekijä', NULL, NULL),
    ('ryhmäavustaja', NULL, NULL),
    ('ryhmäperhepäivähoitaja', NULL, NULL),
    ('sairaanhoitaja', NULL, NULL),
    ('seppä/korjausmies', NULL, NULL),
    ('sihteeriharjoittelija', NULL, NULL),
    ('siistijä', NULL, NULL),
    ('siviilipalvelusmies', NULL, NULL),
    ('sivistys- ja hyvinvointijohtaja', NULL, NULL),
    ('suunnittelijaopettaja', NULL, NULL),
    ('suunnitteluassistentti', NULL, NULL),
    ('suunnitteluinsinööri', NULL, NULL),
    ('suunnittelumestari', NULL, NULL),
    ('suunnittelupäällikkö', NULL, NULL),
    ('sähköasentaja', NULL, NULL),
    ('sähköteknisten töiden valvoja', NULL, NULL),
    ('taidekasvattaja', NULL, NULL),
    ('taidekuraattori', NULL, NULL),
    ('talous- ja hallintosihteeri', NULL, NULL),
    ('talouspäällikkö', NULL, NULL),
    ('taloussihteeri', NULL, NULL),
    ('tapahtumakoordinaattori', NULL, NULL),
    ('tarkastusinsinööri', NULL, NULL),
    ('tarkastuspäällikkö', NULL, NULL),
    ('tekstiilihuoltaja', NULL, NULL),
    ('terveystarkastaja', NULL, NULL),
    ('tiehöylänkuljettaja', NULL, NULL),
    ('tiemestari', NULL, NULL),
    ('tietohallintojohtaja', NULL, NULL),
    ('tietopalvelusihteeri', NULL, NULL),
    ('tietoturva- ja teknologiapäällikkö', NULL, NULL),
    ('toiminnanjohtaja', NULL, NULL),
    ('toimistoinsinööri', NULL, NULL),
    ('toimistomestari', NULL, NULL),
    ('toimistosihteeri', NULL, NULL),
    ('toimitilahuoltaja', NULL, NULL),
    ('toimitilapäällikkö', NULL, NULL),
    ('toimitusinsinööri', NULL, NULL),
    ('traktorinkuljettaja', NULL, NULL),
    ('tukipalvelukoordinaattori', NULL, NULL),
    ('tukipalvelun työntekijä', NULL, NULL),
    ('tuntiopettaja', NULL, NULL),
    ('tuntiopettaja     (päätoiminen)', NULL, NULL),
    ('tuntiopettaja     (sivutoiminen)', NULL, NULL),
    ('tuotannonsuunnittelija', NULL, NULL),
    ('tuotantoassistentti', NULL, NULL),
    ('tuotantopäällikkö', NULL, NULL),
    ('tuotantovastaava', NULL, NULL),
    ('tuottaja', NULL, NULL),
    ('turvallisuuskoordinaattori', NULL, NULL),
    ('turvallisuuspäällikkö', NULL, NULL),
    ('turvallisuusvastaava', NULL, NULL),
    ('tutkija', NULL, NULL),
    ('tvt-asiantuntija', NULL, NULL),
    ('tvt-suunnittelija', NULL, NULL),
    ('työhyvinvointiassistentti', NULL, NULL),
    ('työhyvinvointipäällikkö', NULL, NULL),
    ('työllisyysjohtaja', NULL, NULL),
    ('työnjohtaja', NULL, NULL),
    ('työnsuunnittelija', NULL, NULL),
    ('työpajapäällikkö', NULL, NULL),
    ('työsuojeluvaltuutettu     (päätoiminen)', NULL, NULL),
    ('työsuojeluvaltuutettu-korjausmies', NULL, NULL),
    ('työvalmentaja', NULL, NULL),
    ('uima-avustaja', NULL, NULL),
    ('uimaopettaja', NULL, NULL),
    ('uinnin valvoja', NULL, NULL),
    ('uinninvalvoja-liikunnanohjaaja', NULL, NULL),
    ('vahtimestari', NULL, NULL),
    ('valmennuspäällikkö', NULL, NULL),
    ('valvomonesimies', NULL, NULL),
    ('valvomonhoitaja', NULL, NULL),
    ('valvontaeläinlääkäri', NULL, NULL),
    ('varastonhoitaja', NULL, NULL),
    ('varastotyöntekijä', NULL, NULL),
    ('varhaiskasvatuksen aluejohtaja', NULL, NULL),
    ('varhaiskasvatuksen avustaja', NULL, NULL),
    ('varhaiskasvatuksen erityisopettaja', NULL, NULL),
    ('varhaiskasvatuksen lastenhoitaja', NULL, NULL),
    ('varhaiskasvatuksen opettaja', NULL, NULL),
    ('varhaiskasvatuksen sosionomi', NULL, NULL),
    ('varhaiskasvatusjohtaja', NULL, NULL),
    ('vastaava eläinlääkäri', NULL, NULL),
    ('vastaava eläintenhoitaja', NULL, NULL),
    ('vastaava ict-asiantuntija', NULL, NULL),
    ('vastaava kirjastonhoitaja', NULL, NULL),
    ('vastaava palkkasihteeri', NULL, NULL),
    ('verkkosuunnittelija', NULL, NULL),
    ('viestintäkoordinaattori', NULL, NULL),
    ('viestintäpäällikkö', NULL, NULL),
    ('viestintäsuunnittelija', NULL, NULL),
    ('viheraluesuunnittelija', NULL, NULL),
    ('vihertyöpäällikkö', NULL, NULL),
    ('vuorovaikutussuunnittelija', NULL, NULL),
    ('yhdyskuntarakentaja', NULL, NULL),
    ('yhteisötyöntekijä', NULL, NULL),
    ('yleiskaavapäällikkö', NULL, NULL),
    ('yleisötyön tuottaja', NULL, NULL),
    ('ylläpitopäällikkö', NULL, NULL),
    ('ympäristönsuojelujohtaja', NULL, NULL),
    ('ympäristönsuojelutarkastaja', NULL, NULL),
    ('ympäristöterveysjohtaja', NULL, NULL);    

GO
