CREATE TABLE [dbo].[CRUDChangeLog] (
    [Id] UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    [ObjektiTyyppi] NVARCHAR(255) NOT NULL,
    [ObjektiId] UNIQUEIDENTIFIER NOT NULL,
    [MuokattuKentta] NVARCHAR(255) NOT NULL,
    [VanhaArvo] NVARCHAR(255) NOT NULL,
    [UusiArvo] NVARCHAR(255) NOT NULL,
    [Muokkaaja] NVARCHAR(255) NOT NULL,
    [Timestamp] DATETIME DEFAULT GETDATE() NOT NULL
);

GO
